spring:
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      database: broker-fulfillment-logistics
      uri: mongodb://admin:sb75Gz73@mongodb-dev-oms.eastus.cloudapp.azure.com:27017/admin?socketTimeoutMS=30000&connectTimeoutMS=30000&waitQueueTimeoutMS=30000&maxIdleTimeMS=30000&wtimeoutMS=30000&readPreference=secondaryPreferred
  rabbitmq:
    port: 5672
    host: localhost
    virtual-host: bfl
    username: bfladmin
    password: bfladmin2K19!
    listener:
      simple:
        prefetch: 0
        concurrency: 80
        max-concurrency: 160
        retry:
          initial-interval: 5000
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    service:
      name: ${spring.application.name}
  sleuth:
    sampler:
      probability: 1

management:
  health:
    elasticsearch:
      enabled: false
  metrics:
    export:
      influx:
        db: bfl-service-dev
        #uri: http://10.100.200.170:8086
        uri: http://localhost:8086
        step: 1h
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: loggers

#DEV
oms:
  pagination-branch-size: 100
  wso2Url: https://oms-tester-machine-dev.eastus.cloudapp.azure.com/wso2/token
  wso2ConsumerKey: cJtCjLAOHkvnpIOq2jBYnAqypTQa
  wso2ConsumerSecret: WSDywpRE3HMtSDbQZBAui13c0ksa
  endpoint:
    stock-api: https://oms-tester-machine-dev.eastus.cloudapp.azure.com/ingress/oms/stock-service/v1/
  elastic:
    host: elasticstack-eval.eastus.cloudapp.azure.com
    port: 9200
    username: elastic
    password: OTFkNmRkYzM3
    timeout: 10000

bfl:
  business:
    threadPoolSize: 1000
  endpoint:
    freight-service: https://oms-tester-machine-dev.eastus.cloudapp.azure.com/ingress/oms/bfl-freight-service/v1/
    branch-geolocation-service: https://oms-tester-machine-dev.eastus.cloudapp.azure.com/ingress/oms/bfl-branch-geolocation-service/v1/
    branch-service: https://oms-tester-machine-dev.eastus.cloudapp.azure.com/ingress/oms/branch-service/v1/
    checkout-service: https://oms-tester-machine-dev.eastus.cloudapp.azure.com/ingress/oms/bfl-checkout-service/v1/
    datalake:
      url: https://bifrost.lojasrenner.com.br/
      token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MDM5ODkyNjMsInRvcGljIjoiaW5fcmVubmVyX29tcyIsInVzZXIiOiJyZW5uZXJfb21zIn0.0zVj-Jbzbph2uyLiuD-B8uCroxsdNy1ZBKs4CbVzFRk
      enabled: true
  timeout:
    freight-service: 10000
    branch-geolocation-service: 15000
    branch-service: 100000
    stock-api: 10000
    combinations: 500000
    threads: 600000
    datalake: 20000
    checkout-service: 10000
  loader:
    ttl:
      #millis :(
      branch-office: 60000
      wso2-token: 3480000
  auth:
    token: 58d6b06b748ad6b61a238a9b6320dfa37ffae7e5
  metric:
    #minutes
    inertTimeLimit: 3
    ttl:
      #millis
      validate: 10000
